#!/bin/bash
function SS ()  {
    . ~/root/script/sh/_lib/path.sh
    . ~/root/script/sh/_userlib/path.sh
    . ~/root/script/sh/_lib/file.sh
    #. ~/root/script/sh/color/color.sh
    . /tmp/work/Shell.Rapbian.20180309090000/src/color/color.sh
    local timestamp=`date '+%Y%m%d%H%M%S'`
    local ext=".png"
    local filepath=`Join ${Path[SS]} "$timestamp$ext"`
    mkdir -p "${Path[SS]}"

    scrot -u -b -c -d 5 "$filepath"
    local size_source=`GetSize $filepath`
    echo "$filepath" $size_source "B"
    for q in 0 1 5 10 20 100
    do
        local size3=`printf "%03d" $q`
        local filename=$timestamp"_"$size3$ext
#        local filename="${timestamp}_"`printf "%03d" $q`${ext}
        
        local o_file=`Join ${Path[SS]} "$filename"`
        local i_file=`Join ${Path[SS]} "$timestamp$ext"`
        pngquant --strip --output "$o_file" --quality $q "$i_file"
        local size=`GetSize $o_file`
        local rate=`python3 /tmp/work/Shell.Rapbian.20180309090000/src/_command/Rate.py $size_source $size`
#        echo "$filename" $size"B" $rate
#        echo -e -n "`Color "$filename" "BB"` "

#        echo -e -n "`Color $timestamp 'Y'`"_"`Color $size3 'BY'``Color $ext 'Y'` "
#        echo -e -n "`Color $size 'BG'``Color 'B'` "
#        echo -e "`Color $rate 'BR'``Color '%'`"

        echo -e -n `Color 'Y'`$timestamp"_"`Color 'BY'`$size3`Color 'Y'`$ext" "
        echo -e -n `Color 'BG'`$size`Color`"B "
        echo -e `Color 'BR'`$rate`Color`'%'
    done
}
SS
